## 45 Days ML Journey - Day05

### Encoding categorical data

In [1]:
# import necessary libs

import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/rashida048/Datasets/master/titanic_data.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In the above dataset, we can see categorical columns like `Sex`, `Embarked`, `Pclass`
Things to note that, columns like `Pclass` are already in interger format, therefore no need for Encoding such columns

For encoding `Sex` and `Embarked` different techniques are available:
+ OneHotEncoding
+ LableEncoding
+ BinaryEncoding

### Slight preprocessing ...

In [16]:
remove_cols = [ 'Cabin', 'PassengerId', 'Ticket', 'Name' ]
df.drop(columns=remove_cols, inplace=True)

In [19]:
df.Age = df.Age.fillna(df.Age.mean)

In [25]:
df.Embarked = df.Embarked.fillna(df.Embarked.value_counts().sort_values(ascending=False).reset_index().iloc[0]['Embarked'])

### Performing Encoding on categorical columns

In [26]:
from sklearn.preprocessing import OneHotEncoder

In [36]:
ohe = OneHotEncoder(sparse_output=False, drop='first')
encoded_cols = ohe.fit_transform(df[["Sex", "Embarked"]])

In [38]:
encoded_cols

array([[1., 0., 1.],
       [0., 0., 0.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 1., 0.]])

In [40]:
ohe.get_feature_names_out(["Sex", "Embarked"])

array(['Sex_male', 'Embarked_Q', 'Embarked_S'], dtype=object)

We can perform the exact same task using pd.get_dummies() function.
But that's not recommended because sklearn.preprocessing.OneHotEncoder and requires manual coding while creating pipelines.
<br/>
Below is the demonstration of same.

In [43]:
pd.get_dummies(df[["Sex", "Embarked"]]).head(5)

   Sex_female  Sex_male  Embarked_C  Embarked_Q  Embarked_S
0       False      True       False       False        True
1        True     False        True       False       False
2        True     False       False       False        True
3        True     False       False       False        True
4       False      True       False       False        True

### Label Encoding example

In [44]:
# creating a sample dataframe
test_df = pd.DataFrame({
    "age" : [10, 12, 13, 14, 15, 17],
    "marks": [ 50, 40, 36, 89, 23 , 90 ],
    "result": ["pass", "pass", "pass", "pass", "fail", "pass"]
})

test_df

   age  marks result
0   10     50   pass
1   12     40   pass
2   13     36   pass
3   14     89   pass
4   15     23   fail
5   17     90   pass

In [46]:
from sklearn.preprocessing import LabelEncoder

In [47]:
le = LabelEncoder()
new_result = le.fit_transform(test_df.result)

In [49]:
test_df["result"] = new_result

In [50]:
test_df

   age  marks  result
0   10     50       1
1   12     40       1
2   13     36       1
3   14     89       1
4   15     23       0
5   17     90       1

### How is Binary encoding performed?
By applying custom logic, we can not just apply Binary, but other encoding as well.
<br/>
Below given code segment show the same.

In [59]:
test_df["binary_result"] = test_df.marks.apply(
    (lambda mark: "Grade_A" if mark > 75 else "Grade_B")
)

In [60]:
test_df

   age  marks  result binary_result
0   10     50       1       Grade_B
1   12     40       1       Grade_B
2   13     36       1       Grade_B
3   14     89       1       Grade_A
4   15     23       0       Grade_B
5   17     90       1       Grade_A